version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: museo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    restart: always
    ports:
      - "80:4321" # Mapeamos el puerto 80 (internet) al 4321 de Astro
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/museo_db?schema=public
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: "true"
    depends_on:
      - db

volumes:
  postgres_data: